live_config_reload = true
[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]
[env]
TERM = "xterm-256color"
[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85
blur = true
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
dimensions = { columns = 190, lines = 60 }
option_as_alt = "OnlyLeft"
position = { x = 10, y = 10 }
[font]
size = 14.0
[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
  { key = "Left", mods = "Option", chars = "\u001b\u0062" },
  { key = "Right", mods = "Option", chars = "\u001b\u0066" },
  { key = "b", mods = "Option", chars = "\u0017" },
  { key = "w", mods = "Option", chars = "\u001b\u0064" },
  { key = "k", mods = "Command", chars = "\u000C" },
  { key = "k", mods = "Command", command = { program = "/opt/homebrew/bin/tmux", args = [
    "clear-history",
  ] } },
]
